### ISSUE TITLE
use actual language names in translation from image pane

### ISSUE THREAD

**Issue by RedAuburn** [Bnyro/TranslateYou#306] opened 2023-07-30 15:59 UTC
### Describe your suggested feature

It'd be better if these options had the language name instead of language code, eg. afr -> Afrikaans
![Screenshot_20230730-165526_Translate You](https://github.com/Bnyro/TranslateYou/assets/26939824/4005f9a1-5370-45ba-8ace-ff2795c024a9)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RedAuburn** [comment] 2023-07-30 16:01
It might also be good to rename the pane to something like "Image Translation Packs", as currently it's not clear what exactly the user is downloading

**Comment by Bnyro** [comment] 2023-07-30 16:01
duplicate of #280

**Closed by Bnyro** 2023-07-30 16:01 UTC
Labels: enhancement
