### ISSUE TITLE
Problem with non-latin languages when they're translated to other languages in lingva engine

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/TranslateYou#120] opened 2022-12-26 18:10 UTC
### Steps to reproduce

1. Choose the Lingva engine in settings
2. Choose any non-latin language and start translating from this to any other language

### Expected behavior

Translate should appears correctly

### Actual behavior

Instead of translating, it just repeats the entered text or do nothing at all, like in examples below

### Translate You version

2.7

### Android version

Android 12

### Other details

So, here an examples

![example1](https://user-images.githubusercontent.com/113282550/209574055-3050b966-cdb3-4994-a0b3-5431aeced755.png)
![example2](https://user-images.githubusercontent.com/113282550/209574056-bdc8cbc6-5831-4458-9cc3-fa4cd6e17352.png)
![example3](https://user-images.githubusercontent.com/113282550/209574057-027842a1-f998-4472-afe3-5728661fd33d.png)

Changing the instance doesn't fix this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-27 08:01
Dupe of #59

**Closed by Bnyro** 2022-12-27 08:01 UTC
Labels: bug

**Comment by HotarunIchijou** [comment] 2022-12-27 08:33
Oh, didn't see this
