### ISSUE TITLE
Download option

### ISSUE THREAD

**Issue by heberjeur** [Bnyro/TranslateYou#148] opened 2023-01-27 20:38 UTC
### Describe your suggested feature

Can you add an option to download dictionaries like Google Translate has?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-28 13:32
Duplicate of #18

**Closed by Bnyro** 2023-01-28 13:32 UTC
Labels: enhancement
