### ISSUE TITLE
Pop-up translation 

### ISSUE THREAD

**Issue by MXC48** [Bnyro/TranslateYou#152] opened 2023-01-28 12:55 UTC
### Describe your suggested feature

I find that, like other translation applications, it would be good if when you select text to translate and choose translateYou to do it, the application opens a pop-up and not the entire application. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-28 13:33
Duplicate of #86

**Closed by Bnyro** 2023-01-28 13:33 UTC
Labels: enhancement
