### ISSUE TITLE
Display over other apps & floating button

### ISSUE THREAD

**Issue by K4zoku** [Bnyro/TranslateYou#141] opened 2023-01-18 08:45 UTC
### Describe your suggested feature

It should work like google translate or instalate (open source). Show a floating button that immediately translate clipboard content when clicked, and the translation windows should not be full screen

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-18 17:04
Duplicate of #86

**Closed** 2023-01-18 17:04 UTC
Labels: enhancement
